name: CI

on:
    pull_request:
    push:

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: "Run lint"
              run: pnpm lint

            - name: Run tests
              run: pnpm test
